Repository github-stats-22/github-stats, pull requests merged in 2022-11, with the labels that each got.

#1 Implement Spring Shell (CLI)
  build.gradle
  src/main/java/io/pakland/mdas/githubstats/shell/CustomPromptProvider.java
  src/main/java/io/pakland/mdas/githubstats/shell/components/CommitComponent.java
  src/main/java/io/pakland/mdas/githubstats/shell/components/LinesOfCodeComponent.java
  src/main/java/io/pakland/mdas/githubstats/shell/components/PullRequestComponent.java
Labels: type: chore, status: deploy

#17 Feature base structure
  .gitignore
  build.gradle
  checkstyle.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lombok.config
  mvnw
  src/main/java/io/pakland/mdas/githubstats/GithubStatsApplication.java
  src/main/java/io/pakland/mdas/githubstats/domain/Comment.java
  src/main/java/io/pakland/mdas/githubstats/domain/Commit.java
  src/main/java/io/pakland/mdas/githubstats/domain/Organization.java
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequests.java
  src/main/java/io/pakland/mdas/githubstats/domain/Repository.java
  src/main/java/io/pakland/mdas/githubstats/domain/ReviewUser.java
  src/main/java/io/pakland/mdas/githubstats/domain/Team.java
  src/main/java/io/pakland/mdas/githubstats/domain/User.java
  src/main/java/io/pakland/mdas/githubstats/domain/UserOrganization.java
  src/main/java/io/pakland/mdas/githubstats/domain/UserTeam.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IComment.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/ICommit.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IOrganization.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IPullRequests.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IReviewUser.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/ITeam.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IUser.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IUserOrganization.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IUserTeam.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/db.changelog/db.changelog-master.yaml
  src/main/resources/logback-spring.xml
Labels: type: feat, status: code review

#19 chore!: move gradle config to maven
  README.md
  build.gradle
  mvnw
  pom.xml
  settings.gradle
  src/main/java/io/pakland/mdas/githubstats/domain/Commit.java
  src/main/java/io/pakland/mdas/githubstats/domain/UserOrganization.java
  src/main/java/io/pakland/mdas/githubstats/domain/UserTeam.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IUserOrganization.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IUserTeam.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/test/java/io/pakland/mdas/githubstats/GithubStatsApplicationTests.java
  src/test/java/io/pakland/mdas/githubstats/domain/UserTest.java
Labels: status: code review, type: chore

#24 refactor: apply hexagonal folder structure
  src/main/java/io/pakland/mdas/githubstats/application/.gitkeep
  src/main/java/io/pakland/mdas/githubstats/domain/.gitkeep
  src/main/java/io/pakland/mdas/githubstats/domain/model/Comment.java
  src/main/java/io/pakland/mdas/githubstats/domain/model/Commit.java
  src/main/java/io/pakland/mdas/githubstats/domain/model/Organization.java
  src/main/java/io/pakland/mdas/githubstats/domain/model/PullRequests.java
  src/main/java/io/pakland/mdas/githubstats/domain/model/Repository.java
  src/main/java/io/pakland/mdas/githubstats/domain/model/ReviewUser.java
  src/main/java/io/pakland/mdas/githubstats/domain/model/Team.java
  src/main/java/io/pakland/mdas/githubstats/domain/model/User.java
  src/main/java/io/pakland/mdas/githubstats/domain/ports/CommentRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/ports/CommitRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/ports/OrganizationRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/ports/PullRequestsRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/ports/RepositoryRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/ports/ReviewUserRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/ports/TeamRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/ports/UserRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IComment.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/ICommit.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IOrganization.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IPullRequests.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IReviewUser.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/ITeam.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/IUser.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/.gitkeep
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/CustomPromptProvider.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/CommitComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/LinesOfCodeComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/PullRequestComponent.java
Labels: status: code review, type: refactor

#28 chore: clean terminal
  README.md
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: type: feat, status: code review

#30 docs: team agreements
  .github/PULL_REQUEST_TEMPLATE/default_template.md
  CONTRIBUTING.md
Labels: type: documentation, status: code review

#29 feat: historic table and repository
  src/main/java/io/pakland/mdas/githubstats/domain/model/HistoricQueries.java
  src/main/java/io/pakland/mdas/githubstats/domain/ports/HistoricQueriesRepository.java
Labels: type: feat, status: code review

#35 ci: create Github Action
  .github/workflows/jib-container-publish.yml
Labels: status: code review, type: chore

#44 feat: add `getRepositoriesByTeam` use case
  src/main/java/io/pakland/mdas/githubstats/domain/service/GetRepositoriesByTeam.java
  src/test/java/io/pakland/mdas/githubstats/domain/service/GetRepositoriesByTeamTest.java
Labels: type: feat, status: code review

#46 fix: add missing db migration
  src/main/resources/db/changelog/changes/001_add_team_name.yaml
Labels: type: bug, status: code review
