Repository github-stats-22/github-stats, pull requests merged in 2022-12, with the labels that each got.

#47 feat: add `AggregateUserReviews` use case
  src/main/java/io/pakland/mdas/githubstats/application/AggregateUserReviews.java
  src/main/java/io/pakland/mdas/githubstats/domain/UserReview.java
  src/main/java/io/pakland/mdas/githubstats/domain/UserReviewAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/UserReviewRepository.java
  src/test/java/io/pakland/mdas/githubstats/application/AggregateUserReviewsTest.java
  src/test/java/io/pakland/mdas/githubstats/application/GetOrganizationFromIdTest.java
  src/test/java/io/pakland/mdas/githubstats/application/GetOrganizationFromTeamNameTest.java
  src/test/java/io/pakland/mdas/githubstats/application/GetRepositoriesByTeamTest.java
  src/test/java/io/pakland/mdas/githubstats/application/GetTeamsFromOrganizationTest.java
Labels: type: feat, status: code review

#53 feat: `fetchUsersFromTeam` use case
  pom.xml
  src/main/java/io/pakland/mdas/githubstats/application/dto/UserDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/WebClientConfiguration.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/adapters/UserRESTRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/ports/IUserRESTRepository.java
  src/main/resources/application.yml
  src/test/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/UserRESTRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/responses/TeamMembers.json
Labels: type: feat, status: code review

#57 feat: add `SaveRepository` use case
  src/main/java/io/pakland/mdas/githubstats/application/SaveOrganization.java
  src/test/java/io/pakland/mdas/githubstats/application/SaveOrganizationTest.java
Labels: type: feat, status: code review

#58 chore: add ci action
  .github/workflows/ci.yaml
Labels: status: code review, type: chore

#60 Feat/fetch organizations from api key
  src/main/java/io/pakland/mdas/githubstats/application/dto/OrganizationDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/adapters/OrganizationRESTRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/ports/IOrganizationRESTRepository.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/OrganizationRESTRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/responses/AvailableOrganizations.json
Labels: type: feat, status: code review

#61 feat: fetch teams from organization user case
  src/main/java/io/pakland/mdas/githubstats/application/dto/TeamDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/adapters/TeamRESTRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/ports/ITeamRESTRepository.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/TeamRESTRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/rest/repository/responses/OrganizationTeams.json
Labels: type: feat, status: code review

#64 Small object Ids refactor and extract external repository use cases
  src/main/java/io/pakland/mdas/githubstats/FetchUsersFromTeam.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchAvailableOrganizations.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchRepositoriesFromTeam.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchTeamsFromOrganization.java
  src/main/java/io/pakland/mdas/githubstats/application/GetOrganizationFromId.java
  src/main/java/io/pakland/mdas/githubstats/application/GetOrganizationFromTeamName.java
  src/main/java/io/pakland/mdas/githubstats/application/exceptions/OrganizationNotFound.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/RepositoryMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/TeamMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/UserMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/Comment.java
  src/main/java/io/pakland/mdas/githubstats/domain/Commit.java
  src/main/java/io/pakland/mdas/githubstats/domain/HistoricQueries.java
  src/main/java/io/pakland/mdas/githubstats/domain/Organization.java
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/domain/Repository.java
  src/main/java/io/pakland/mdas/githubstats/domain/Team.java
  src/main/java/io/pakland/mdas/githubstats/domain/User.java
  src/main/java/io/pakland/mdas/githubstats/domain/UserReview.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/CommentRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/CommitRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/HistoricQueriesRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/OrganizationRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/PullRequestsRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/RepositoryExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/RepositoryRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/TeamExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/TeamRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/UserExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/UserRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/UserReviewRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/controller/UserOptionController.java
  src/main/resources/db/changelog/changes/000_initial_schema.yaml
  src/main/resources/db/changelog/changes/001_add_team_name.yaml
  src/main/resources/db/sql/.gitkeep
  src/main/resources/db/sql/inserts.sql
  src/test/java/io/pakland/mdas/githubstats/application/GetOrganizationFromIdTest.java
  src/test/java/io/pakland/mdas/githubstats/application/GetOrganizationFromTeamNameTest.java
  src/test/java/io/pakland/mdas/githubstats/application/GetRepositoriesByTeamTest.java
  src/test/java/io/pakland/mdas/githubstats/application/GetTeamsFromOrganizationTest.java
  src/test/java/io/pakland/mdas/githubstats/application/SaveOrganizationTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepositoryTest.java
Labels: type: bug, status: code review

#72 feat: fetch multiple pull request pages
  src/main/java/io/pakland/mdas/githubstats/application/FetchPullRequestsFromRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequestState.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/PullRequestExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/PullRequestGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/controller/UserOptionController.java
  src/main/resources/db/changelog/changes/000_initial_schema.yaml
  src/test/java/io/pakland/mdas/githubstats/application/FetchPullRequestFromRepositoryTest.java
Labels: type: feat, status: done

#71 feat: add `AggregateCommits` use case
  src/main/java/io/pakland/mdas/githubstats/application/AggregateCommits.java
  src/main/java/io/pakland/mdas/githubstats/domain/CommitAggregation.java
  src/test/java/io/pakland/mdas/githubstats/application/AggregateCommitsTest.java
Labels: type: feat, status: deploy

#79 feat: merge teams into pull requests
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/domain/Repository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/controller/UserOptionController.java
Labels: type: feat, status: deploy

#94 feat: add `SaveAllPullRequests` use case
  src/main/java/io/pakland/mdas/githubstats/application/SaveAllPullRequests.java
  src/test/java/io/pakland/mdas/githubstats/application/SaveAllPullRequestsTest.java
Labels: type: feat, status: done

#90 fix: add missing @service spring annotation
  src/main/java/io/pakland/mdas/githubstats/application/FetchAvailableOrganizations.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchPullRequestsFromRepository.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchRepositoriesFromTeam.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchTeamsFromOrganization.java
  src/main/java/io/pakland/mdas/githubstats/application/SaveAllCommits.java
Labels: type: bug, status: deploy

#91 feat: add `SaveAllRepositories` use case
  src/main/java/io/pakland/mdas/githubstats/application/SaveAllRepositories.java
  src/test/java/io/pakland/mdas/githubstats/application/SaveAllRepositoriesTest.java
Labels: type: feat, status: done

#103 docs: updated `README.md` with new instructions
  README.md
Labels: type: documentation, status: code review

#102 feat: database user controller
  src/main/java/io/pakland/mdas/githubstats/application/AggregateUserReviews.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchUsersFromTeam.java
  src/main/java/io/pakland/mdas/githubstats/application/GetOrganizationFromId.java
  src/main/java/io/pakland/mdas/githubstats/application/GetUserByLogin.java
  src/main/java/io/pakland/mdas/githubstats/application/OrchestrateAggregators.java
  src/main/java/io/pakland/mdas/githubstats/application/exceptions/.gitkeep
  src/main/java/io/pakland/mdas/githubstats/application/exceptions/UserLoginNotFound.java
  src/main/java/io/pakland/mdas/githubstats/application/unnused/GetOrganizationFromTeamName.java
  src/main/java/io/pakland/mdas/githubstats/application/unnused/GetRepositoriesByTeam.java
  src/main/java/io/pakland/mdas/githubstats/application/unnused/GetTeamsFromOrganization.java
  src/main/java/io/pakland/mdas/githubstats/domain/.gitkeep
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/domain/User.java
  src/main/java/io/pakland/mdas/githubstats/domain/UserReview.java
  src/main/java/io/pakland/mdas/githubstats/domain/UserReviewAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/UserRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/.gitkeep
  src/main/java/io/pakland/mdas/githubstats/infrastructure/controller/UserControllerFromDb.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/controller/UserControllerFromGithub.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/UserOptionComponent.java
  src/test/java/io/pakland/mdas/githubstats/application/AggregateUserReviewsTest.java
  src/test/java/io/pakland/mdas/githubstats/application/GetOrganizationFromIdTest.java
  src/test/java/io/pakland/mdas/githubstats/application/GetOrganizationFromTeamNameTest.java
  src/test/java/io/pakland/mdas/githubstats/application/GetRepositoriesByTeamTest.java
  src/test/java/io/pakland/mdas/githubstats/application/GetTeamsFromOrganizationTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepositoryTest.java
Labels: type: feat, status: wip

#108 Fix/missing attibutes
  src/main/java/io/pakland/mdas/githubstats/application/OrchestrateAggregators.java
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequest.java
  src/main/resources/db/changelog/changes/000_initial_schema.yaml
Labels: type: bug, status: code review

#109 feat: request full commit data from pr list
  src/main/java/io/pakland/mdas/githubstats/domain/Commit.java
  src/main/java/io/pakland/mdas/githubstats/domain/CommitAggregation.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommitGitHubRepository.java
  src/main/resources/db/changelog/changes/000_initial_schema.yaml
Labels: type: feat, status: code review

#117 refactor: replace `for:in` over lambdas
  src/main/java/io/pakland/mdas/githubstats/infrastructure/controller/UserControllerFromGithub.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubUserOptionController.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubUserOptionRequest.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/UserOptionComponent.java
Labels: status: code review, type: refactor

#122 fix: remove @JsonProperty from Comment Entity
  src/main/java/io/pakland/mdas/githubstats/application/dto/CommentDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/CommentMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Comment.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubCommentDTO.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/CommentMapperTest.java
Labels: type: bug, status: code review

#119 fix: remove `JsonProperty` from `User` entity
  src/main/java/io/pakland/mdas/githubstats/application/dto/UserDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/external/FetchUsersFromTeam.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/UserMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/User.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubUserDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepository.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/UserMapperTest.java
Labels: type: bug, status: code review

#127 refactor: run use cases in `UserControllerFromDb`
  src/main/java/io/pakland/mdas/githubstats/application/internal/AggregatePullRequests.java
  src/main/java/io/pakland/mdas/githubstats/application/internal/OrchestrateAggregators.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/CSVExportable.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/CommitAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequestAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/UserReviewAggregation.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/controller/UserControllerFromDb.java
  src/test/java/io/pakland/mdas/githubstats/domain/CSVTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/CommitAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/PullRequestAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/UserReviewAggregationTest.java
Labels: status: code review, type: refactor

#129 fix: update yml liquidbase
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Commit.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequest.java
  src/main/resources/application.yml
  src/main/resources/db/changelog/changes/000_initial_schema.yaml
Labels: type: bug, status: code review

#136 fix: remove `JsonProperty` from `Team` entity
  src/main/java/io/pakland/mdas/githubstats/application/dto/TeamDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/TeamMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Team.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubTeamDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepository.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/TeamMapperTest.java
Labels: type: bug, status: code review

#137 fix: remove `JsonProperty` from `PullRequest`
  src/main/java/io/pakland/mdas/githubstats/application/dto/PullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/PullRequestGitHubRepository.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapperTest.java
Labels: type: bug, status: code review

#138 fix: remove `JsonProperty` from `PullRequestState`
  src/main/java/io/pakland/mdas/githubstats/application/dto/PullRequestStateDTO.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequestState.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestStateDTO.java
Labels: type: bug, status: code review

#140 fix: remove `JsonProperty` from `Repository`
  src/main/java/io/pakland/mdas/githubstats/application/dto/RepositoryDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/RepositoryMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Repository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubRepositoryDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/RepositoryGitHubRepository.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/RepositoryMapperTest.java
Labels: type: bug, status: code review

#144 refactor: hydrate entities inside infra layer
  src/main/java/io/pakland/mdas/githubstats/application/external/FetchCommitsFromPullRequest.java
  src/main/java/io/pakland/mdas/githubstats/application/external/FetchPullRequestsFromRepository.java
  src/main/java/io/pakland/mdas/githubstats/application/external/FetchRepositoriesFromTeam.java
  src/main/java/io/pakland/mdas/githubstats/application/external/FetchTeamsFromOrganization.java
  src/main/java/io/pakland/mdas/githubstats/application/external/FetchUsersFromTeam.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Commit.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Repository.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Team.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubUserOptionController.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchCommitsFromPullRequestTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchPullRequestFromRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchRepositoriesFromTeamTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchTeamsFromOrganizationTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchUsersFromTeamTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepositoryTest.java
Labels: status: code review, type: refactor

#163 feat: map `User` to entities
  src/main/java/io/pakland/mdas/githubstats/application/dto/CommitDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/dto/PullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/dto/ReviewDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/external/FetchReviewsFromPullRequest.java
  src/main/java/io/pakland/mdas/githubstats/application/internal/AggregateReviews.java
  src/main/java/io/pakland/mdas/githubstats/application/internal/AggregateUserReviews.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/CommitMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/ReviewMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/UserMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Comment.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Commit.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Review.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/ReviewAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/User.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/ReviewExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubController.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubCommitDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubReviewDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommitGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/PullRequestGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/ReviewGitHubRepository.java
  src/test/java/io/pakland/mdas/githubstats/application/internal/AggregateReviewsTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/ReviewAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/UserReviewAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepositoryTest.java
Labels: type: feat, status: code review

#167 feat: user review aggregation now distinguishes internal/external reviews
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Review.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/ReviewAggregation.java
  src/test/java/io/pakland/mdas/githubstats/application/internal/AggregateReviewsTest.java
Labels: type: feat, status: done

#171 test: remove all testing
  .github/workflows/ci.yaml
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchCommitsFromPullRequestTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchPullRequestFromRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchRepositoriesFromTeamTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchTeamsFromOrganizationTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchUsersFromTeamTest.java
  src/test/java/io/pakland/mdas/githubstats/application/internal/AggregateCommitsTest.java
  src/test/java/io/pakland/mdas/githubstats/application/internal/AggregateReviewsTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/CommentMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/OrganizationMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/RepositoryMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/TeamMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/UserMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/CSVTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/CommitAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/OrganizationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/PullRequestAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/ReviewAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/TeamTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/UserTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/lib/InternalCachingTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/OrganizationGitHubRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/responses/AvailableOrganizations.json
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/responses/OrganizationTeams.json
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/responses/TeamMembers.json
  src/test/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/DateValidatorTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/TeamNameValidatorTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/UserNameValidatorTest.java
Labels: type: feat, status: code review

#177 [PROPOSAL] feat: alternative to `Review`s per user
  src/main/java/io/pakland/mdas/githubstats/application/internal/AggregateReviews.java
Labels: type: feat, status: code review

#178 [PROPOSAL] feat: alternative to `Commit`s per user
  .github/workflows/ci.yaml
  src/main/java/io/pakland/mdas/githubstats/application/internal/AggregateCommits.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchCommitsFromPullRequestTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchPullRequestFromRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchRepositoriesFromTeamTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchTeamsFromOrganizationTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchUsersFromTeamTest.java
  src/test/java/io/pakland/mdas/githubstats/application/internal/AggregateCommitsTest.java
  src/test/java/io/pakland/mdas/githubstats/application/internal/AggregateReviewsTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/CommentMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/OrganizationMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/RepositoryMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/TeamMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/UserMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/CSVTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/CommitAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/OrganizationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/PullRequestAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/ReviewAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/TeamTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/UserTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/lib/InternalCachingTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/OrganizationGitHubRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/responses/AvailableOrganizations.json
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/responses/OrganizationTeams.json
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/responses/TeamMembers.json
  src/test/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/DateValidatorTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/TeamNameValidatorTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/UserNameValidatorTest.java
Labels: type: feat, status: code review

#179 [PROPOSAL] feat: alternative to `PullRequest`s per user
  .github/workflows/ci.yaml
  src/main/java/io/pakland/mdas/githubstats/application/internal/AggregatePullRequests.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchCommitsFromPullRequestTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchPullRequestFromRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchRepositoriesFromTeamTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchTeamsFromOrganizationTest.java
  src/test/java/io/pakland/mdas/githubstats/application/external/FetchUsersFromTeamTest.java
  src/test/java/io/pakland/mdas/githubstats/application/internal/AggregateCommitsTest.java
  src/test/java/io/pakland/mdas/githubstats/application/internal/AggregateReviewsTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/CommentMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/OrganizationMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/RepositoryMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/TeamMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/application/mappers/UserMapperTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/CSVTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/CommitAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/OrganizationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/PullRequestAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/ReviewAggregationTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/TeamTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/entity/UserTest.java
  src/test/java/io/pakland/mdas/githubstats/domain/lib/InternalCachingTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/OrganizationGitHubRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepositoryTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/responses/AvailableOrganizations.json
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/responses/OrganizationTeams.json
  src/test/java/io/pakland/mdas/githubstats/infrastructure/github/repository/responses/TeamMembers.json
  src/test/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/DateValidatorTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/TeamNameValidatorTest.java
  src/test/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/UserNameValidatorTest.java
Labels: type: feat, status: code review

#168 feat: add `ReviewAggregation` grouping by `User` and `Team`
  src/main/java/io/pakland/mdas/githubstats/application/internal/AggregateReviews.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/ReviewAggregation.java
Labels: type: feat, status: code review

#174 feat: add `CommitAggregation` grouping by `User` and `Team`
  src/main/java/io/pakland/mdas/githubstats/application/internal/AggregateCommits.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/CommitAggregation.java
Labels: type: feat, status: code review

#175 feat: add `PullRequestAggregation` grouping by `User` and `Team`
  src/main/java/io/pakland/mdas/githubstats/application/internal/AggregatePullRequests.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequestAggregation.java
Labels: type: feat, status: code review

#176 feat: aggregate `PullRequest` created within range
  src/main/java/io/pakland/mdas/githubstats/application/dto/PullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/internal/AggregatePullRequests.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequestAggregation.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubController.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/PullRequestGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/DateValidator.java
Labels: type: feat, status: code review

#181 fix: type error
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubController.java
Labels: type: feat, status: code review

#182 Feat: export array of `Metric` to csv file
  src/main/java/io/pakland/mdas/githubstats/application/internal/MetricCsvExporter.java
  src/main/java/io/pakland/mdas/githubstats/application/internal/MetricExporter.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/CSVExportable.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Metric.java
Labels: type: feat, status: code review

#190 fix: Replace `commit` for pr detail
  src/main/java/io/pakland/mdas/githubstats/application/dto/CommitDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/dto/PullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/external/FetchCommentsFromPullRequest.java
  src/main/java/io/pakland/mdas/githubstats/application/external/FetchCommitsFromPullRequestInDateRange.java
  src/main/java/io/pakland/mdas/githubstats/application/internal/AggregateCommits.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/CommitMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Commit.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/CommitAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/CommitExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubController.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubCommitDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommitGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/PullRequestGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/ReviewGitHubRepository.java
Labels: type: bug, status: code review

#191 refactor: project structure
  src/main/java/io/pakland/mdas/githubstats/application/AggregatePullRequests.java
  src/main/java/io/pakland/mdas/githubstats/application/AggregateReviews.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchAvailableOrganizations.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchCommentsFromPullRequest.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchPullRequestsInPeriodFromRepository.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchRepositoriesFromTeam.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchReviewsFromPullRequest.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchTeamsFromOrganization.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchUsersFromTeam.java
  src/main/java/io/pakland/mdas/githubstats/application/MetricCsvExporter.java
  src/main/java/io/pakland/mdas/githubstats/application/MetricExporter.java
  src/main/java/io/pakland/mdas/githubstats/application/dto/PullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/dto/PullRequestStateDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/CommentMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/OrganizationMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/RepositoryMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/ReviewMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/TeamMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/UserMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/Comment.java
  src/main/java/io/pakland/mdas/githubstats/domain/DateRange.java
  src/main/java/io/pakland/mdas/githubstats/domain/EntityType.java
  src/main/java/io/pakland/mdas/githubstats/domain/HistoricQueries.java
  src/main/java/io/pakland/mdas/githubstats/domain/Metric.java
  src/main/java/io/pakland/mdas/githubstats/domain/Organization.java
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequestAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequestState.java
  src/main/java/io/pakland/mdas/githubstats/domain/Repository.java
  src/main/java/io/pakland/mdas/githubstats/domain/Review.java
  src/main/java/io/pakland/mdas/githubstats/domain/ReviewAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/Team.java
  src/main/java/io/pakland/mdas/githubstats/domain/User.java
  src/main/java/io/pakland/mdas/githubstats/domain/entity/Repository.java
  src/main/java/io/pakland/mdas/githubstats/domain/exceptions/.gitkeep
  src/main/java/io/pakland/mdas/githubstats/domain/repository/CommentExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/HistoricQueriesRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/MetricRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/OrganizationExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/PullRequestExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/RepositoryExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/ReviewExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/TeamExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/UserExternalRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/utils/InternalCaching.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubController.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPageablePullRequestRequest.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestStateDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommentGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/OrganizationGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/PullRequestGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/RepositoryGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/ReviewGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/postgres/PostgresMiddleware.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellUserComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/ShellRequest.java
Labels: status: code review, type: refactor

#193 feat: apply user options to controller
  src/main/java/io/pakland/mdas/githubstats/application/AggregateComments.java
  src/main/java/io/pakland/mdas/githubstats/application/AggregatePullRequests.java
  src/main/java/io/pakland/mdas/githubstats/application/AggregateReviews.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchCommentsFromPullRequest.java
  src/main/java/io/pakland/mdas/githubstats/application/FetchReviewsFromPullRequest.java
  src/main/java/io/pakland/mdas/githubstats/application/dto/CommentDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/dto/ReviewDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/CommentMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/ReviewMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/Comment.java
  src/main/java/io/pakland/mdas/githubstats/domain/CommentAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/HistoricQueries.java
  src/main/java/io/pakland/mdas/githubstats/domain/OptionType.java
  src/main/java/io/pakland/mdas/githubstats/domain/Organization.java
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/domain/Review.java
  src/main/java/io/pakland/mdas/githubstats/domain/ReviewAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/Team.java
  src/main/java/io/pakland/mdas/githubstats/domain/User.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubController.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubMiddleware.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubCommentDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubOptionRequest.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubReviewDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubUserOptionRequest.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommentGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/postgres/PostgresMiddleware.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellOrganizationComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellTeamComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellUserComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/configuration/CommandConfiguration.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/CommandRegistrationBuilder.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/ShellRequest.java
Labels: type: feat, status: code review

#194 feat: merge aggregates
  result.csv
  src/main/java/io/pakland/mdas/githubstats/application/AggregatePullRequests.java
  src/main/java/io/pakland/mdas/githubstats/application/AggregateReviews.java
  src/main/java/io/pakland/mdas/githubstats/application/MergeAggregatesIntoMetrics.java
  src/main/java/io/pakland/mdas/githubstats/application/MetricCsvExporter.java
  src/main/java/io/pakland/mdas/githubstats/application/dto/PullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/dto/ReviewDTO.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/PullRequestMapper.java
  src/main/java/io/pakland/mdas/githubstats/application/mappers/ReviewMapper.java
  src/main/java/io/pakland/mdas/githubstats/domain/Authored.java
  src/main/java/io/pakland/mdas/githubstats/domain/Comment.java
  src/main/java/io/pakland/mdas/githubstats/domain/CommentAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/Metric.java
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequest.java
  src/main/java/io/pakland/mdas/githubstats/domain/PullRequestAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/Review.java
  src/main/java/io/pakland/mdas/githubstats/domain/ReviewAggregation.java
  src/main/java/io/pakland/mdas/githubstats/domain/Team.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubController.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubPullRequestDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubReviewDTO.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommentGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellOrganizationComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellTeamComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellUserComponent.java
  src/main/resources/db/changelog/changes/000_initial_schema.yaml
Labels: type: feat, status: code review

#196 refactor: dates to yearmonth
  result.csv
  src/main/java/io/pakland/mdas/githubstats/application/MergeAggregatesIntoMetrics.java
  src/main/java/io/pakland/mdas/githubstats/domain/HistoricQueries.java
  src/main/java/io/pakland/mdas/githubstats/domain/Metric.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/HistoricQueriesRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/MetricRepository.java
  src/main/java/io/pakland/mdas/githubstats/domain/utils/YearMonthDateAttributeConverter.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubMiddleware.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/ShellRequest.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/DateValidator.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/NameValidator.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/TeamNameValidator.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/YearMonthValidator.java
  src/main/resources/application.yml
  src/main/resources/db/changelog/changes/000_initial_schema.yaml
Labels: status: code review, type: refactor

#195 feat: add possibility to have custom output path
  .gitignore
  result.csv
  src/main/java/io/pakland/mdas/githubstats/application/ExportMetricsToFile.java
  src/main/java/io/pakland/mdas/githubstats/domain/repository/FileMetricExporter.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubController.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubMiddleware.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubOptionRequest.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/GitHubMetricCsvExporter.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/configuration/CommandConfiguration.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/BaseCommandRegistration.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/CommandRegistrationBuilder.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/FileNameCommandRegistration.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/FromDateCommandRegistration.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/ShellRequest.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/ToDateCommandRegistration.java
Labels: type: feat, status: code review

#197 feat: add loggers and silencer to logger
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubController.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/controller/GitHubMiddleware.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/model/GitHubOptionRequest.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/CommentGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/OrganizationGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/PullRequestGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/RepositoryGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/ReviewGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/TeamGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/UserGitHubRepository.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/github/repository/WebClientConfiguration.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/components/ShellComponent.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/configuration/CommandConfiguration.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/LoggerSilencerCommandRegistration.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/model/ShellRequest.java
  src/main/java/io/pakland/mdas/githubstats/infrastructure/shell/validation/YearMonthValidator.java
Labels: type: feat, status: code review
